[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "5twgnabWrczavTT1nFAX7EMmxPEfFzb9jrzRADQnzGum"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/shryesth/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
